### PR TITLE
adjusted libvirt config to support tcp listening

### PR DESCRIPTION
**Pull request by abdulrahmantkhalifa**
this is used for vm migration
relates to issue https://github.com/zero-os/0-orchestrator/issues/215

### CODE REVIEW

**Comment by maxux** [comment]
I'm not sur the fix is the right behavior, according to the documentation:
```
#
# Network connectivity controls
#

# Flag listening for secure TLS connections on the public TCP/IP port.
# NB, must pass the --listen flag to the libvirtd process for this to
# have any effect.
#
# It is necessary to setup a CA and issue server certificates before
# using this capability.
#
# This is enabled by default, uncomment this to disable it
#listen_tls = 0

# Listen for unencrypted TCP connections on the public TCP/IP port.
# NB, must pass the --listen flag to the libvirtd process for this to
# have any effect.
#
# Using the TCP socket requires SASL authentication by default. Only
# SASL mechanisms which support data encryption are allowed. This is
# DIGEST_MD5 and GSSAPI (Kerberos5)
#
# This is disabled by default, uncomment this to enable it.
#listen_tcp = 1
```

Are you sur you want to disable TLS and enable unencrypted connections ?
Btw, are you sur you want to expose libvirtd unencrypted on **all** interface, which includes public access if the machine got public ip address.

I think at least you should uncomment `#listen_addr = "192.168.0.1"` and set it to `127.0.0.1` ?

**Comment by muhamadazmy** [comment]
@abdulrahmantkhalifa @maxux @grimpy may be it's better to have `ssh` on 0-core nodes, but we will have to figure out how we should exchange the keys.

**Comment by abdulrahmantkhalifa** [comment]
can we wait on this until it is dicussed ,

**Comment by muhamadazmy** [comment]
## Suggestion

- Have `ssh` client as part of initramfs
- On boot, ays will generate a new private/public key pair for the node
- It uploads the public key to the node `/root/.ssh/authorized_keys` file

- When a migrate is requested via the API, the migrate blueprint will fetch the target machine private key from the ays repo, and send it along the 0-core migrate call.
- The migrate call will use the qemu+ssh:// protocol instead of tcp and make sure the ssh client will use the provided private key.

@FastGeert ?

**Comment by grimpy** [comment]
I'm not sure we need to have `ssh` client on the of for the qemu+ssh protocol to work? Just need to make sure libvirtd is built with support for it.

**Comment by muhamadazmy** [comment]
@grimpy I wasn't sure either, but @abdulrahmantkhalifa and @mie00 claims it's needed.

**Comment by maxux** [comment]
Do you think we should drop `dropbear` and put `openssh` (client/server) in place ?

**Comment by abdulrahmantkhalifa** [comment]
concerning the `ssh` client being required , here is the error we bypassed by installing the ssh client 
```"failed to start a qemu connection: virError(Code=38, Domain=0, Message='Cannot find 'ssh' in path: No such file or directory')"``` @grimpy

**Comment by grimpy** [comment]
@maxux I don't think it will incease the footprint much right?

**Comment by grimpy** [comment]
Ok we need to get the ball rolling on this one again, I agree with the suggestion made by @muhamadazmy execept I dont think we need to pass the private key along, aslong we are storing it in the default location of root /root/.ssh it will be used automaticly.
+1 on adding full openssh toold which is needed for ssh-keygen aswell.

**Comment by zaibon** [comment]
Agree with that approach. But how are we going to do to distribute the keys to all the nodes? 
Can we avoid sending private keys around ?

**Comment by grimpy** [comment]
@zaibon it would do this at runtime, so when doing a migrate the ays services knows the source and destination, if need it can generate the keys at this time and make sure the destination has the public key of the source configured.

**Comment by maxux** [comment]
I close this PR. This is not relevant anymore.
Please open an issue if any further information are needed.

**Pull request closed without merging**
